apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: civo-docs
    app.kubernetes.io/instance: poc
  name: civo-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: civo-docs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: civo-docs
    spec:
      containers:
      - image: civobot/civo-docs:${IMAGE_TAG}
        name: docusaurus
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 3
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
      imagePullSecrets:
      - name: docker-regcred